[26-Feb-2022 13:51:09 Asia/Manila] PHP Fatal error:  Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /home1/johnpalencia/dgpos.app/admin/print/htmlToPdf.php:1) in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php:271
Stack trace:
#0 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1053): FPDF->Error('Some data has a...')
#1 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1000): FPDF->_checkoutput()
#2 /home1/johnpalencia/dgpos.app/admin/print/customReportPDF.php(126): FPDF->Output()
#3 {main}
  thrown in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php on line 271
[26-Feb-2022 14:07:20 Asia/Manila] PHP Fatal error:  Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /home1/johnpalencia/dgpos.app/admin/print/htmlToPdf.php:1) in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php:271
Stack trace:
#0 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1053): FPDF->Error('Some data has a...')
#1 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1000): FPDF->_checkoutput()
#2 /home1/johnpalencia/dgpos.app/admin/print/customReportPDF.php(126): FPDF->Output()
#3 {main}
  thrown in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php on line 271
[26-Feb-2022 14:12:13 Asia/Manila] PHP Fatal error:  Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /home1/johnpalencia/dgpos.app/admin/print/htmlToPdf.php:1) in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php:271
Stack trace:
#0 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1053): FPDF->Error('Some data has a...')
#1 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1000): FPDF->_checkoutput()
#2 /home1/johnpalencia/dgpos.app/admin/print/customReportPDF.php(126): FPDF->Output()
#3 {main}
  thrown in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php on line 271
[26-Feb-2022 14:12:51 Asia/Manila] PHP Fatal error:  Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /home1/johnpalencia/dgpos.app/admin/print/htmlToPdf.php:1) in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php:271
Stack trace:
#0 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1053): FPDF->Error('Some data has a...')
#1 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1000): FPDF->_checkoutput()
#2 /home1/johnpalencia/dgpos.app/admin/print/customReportPDF.php(126): FPDF->Output()
#3 {main}
  thrown in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php on line 271
[26-Feb-2022 14:13:19 Asia/Manila] PHP Fatal error:  Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /home1/johnpalencia/dgpos.app/admin/print/htmlToPdf.php:1) in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php:271
Stack trace:
#0 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1053): FPDF->Error('Some data has a...')
#1 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1000): FPDF->_checkoutput()
#2 /home1/johnpalencia/dgpos.app/admin/print/customReportPDF.php(126): FPDF->Output()
#3 {main}
  thrown in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php on line 271
[26-Feb-2022 14:15:44 Asia/Manila] PHP Fatal error:  Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /home1/johnpalencia/dgpos.app/admin/print/htmlToPdf.php:1) in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php:271
Stack trace:
#0 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1053): FPDF->Error('Some data has a...')
#1 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1000): FPDF->_checkoutput()
#2 /home1/johnpalencia/dgpos.app/admin/print/customReportPDF.php(126): FPDF->Output()
#3 {main}
  thrown in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php on line 271
[26-Feb-2022 14:21:32 Asia/Manila] PHP Fatal error:  Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /home1/johnpalencia/dgpos.app/admin/print/htmlToPdf.php:1) in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php:271
Stack trace:
#0 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1053): FPDF->Error('Some data has a...')
#1 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1000): FPDF->_checkoutput()
#2 /home1/johnpalencia/dgpos.app/admin/print/customReportPDF.php(126): FPDF->Output()
#3 {main}
  thrown in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php on line 271
[27-Feb-2022 01:15:01 Asia/Manila] PHP Fatal error:  Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /home1/johnpalencia/dgpos.app/admin/print/htmlToPdf.php:1) in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php:271
Stack trace:
#0 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1053): FPDF->Error('Some data has a...')
#1 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1000): FPDF->_checkoutput()
#2 /home1/johnpalencia/dgpos.app/admin/print/customReportPDF.php(126): FPDF->Output()
#3 {main}
  thrown in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php on line 271
[27-Feb-2022 01:16:20 Asia/Manila] PHP Fatal error:  Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /home1/johnpalencia/dgpos.app/admin/print/htmlToPdf.php:1) in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php:271
Stack trace:
#0 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1053): FPDF->Error('Some data has a...')
#1 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1000): FPDF->_checkoutput()
#2 /home1/johnpalencia/dgpos.app/admin/print/customReportPDF.php(126): FPDF->Output()
#3 {main}
  thrown in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php on line 271
[27-Feb-2022 01:20:40 Asia/Manila] PHP Fatal error:  Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /home1/johnpalencia/dgpos.app/admin/print/htmlToPdf.php:1) in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php:271
Stack trace:
#0 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1053): FPDF->Error('Some data has a...')
#1 /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php(1000): FPDF->_checkoutput()
#2 /home1/johnpalencia/dgpos.app/admin/print/customReportPDF.php(126): FPDF->Output()
#3 {main}
  thrown in /home1/johnpalencia/dgpos.app/resources/fpdf/fpdf.php on line 271
